### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by DanielLyi** [JStocke12/CustomPool#1]
Hi.
I would like to contribute to your project. What are you making your game for?
Danylo

**Comment by JStocke12** [comment]
Hi Danylo,
I'm making my project for school, but I'd be very interested in your help! I'll contact my teacher about potentially bringing other people onto this project.
JStocke12

**Comment by JStocke12** [comment]
Unfortunately, my teacher said that I probably shouldn't let other people onto the project, but feel free to copy!
